OCAMLFLAGS +=  -linkpkg -bin-annot -g 



PACKS = Z3



# SOURCES = extensions.ml m.ml list_map.ml s.ml id.ml syntax.ml formula.ml formula_eq.ml deformation.ml useZ3.ml find_unknownP.ml \
# type.ml preSyntax.ml data_info.mli data_info.ml  mk_tmp.ml parser.mly lexer.mll preprocess.ml\
#  ml.mli ml.ml taSyntaxl.mli taSyntax.ml typeInfer.mli typeInfer.ml\
#  main.ml 
# RESULT = liquid_infer


SOURCES = extensions.ml m.ml list_map.ml s.ml id.ml syntax.ml formula.ml formula_eq.ml \
deformation.ml useZ3.ml find_unknownP.ml \
type.ml preSyntax.ml data_info.mli data_info.ml  mk_tmp.ml parser.mly lexer.mll preprocess.ml\
taSyntax.mli taSyntax.ml ml.mli ml.ml typeInfer.mli typeInfer.ml \
 main_ml_infer.ml 
RESULT = liquid_infer



include OCamlMakefile


